export const articleMockData = {
  status: "OK",
  copyright:
    "Copyright (c) 2024 The New York Times Company.  All Rights Reserved.",
  num_results: 20,
  results: [
    {
      uri: "nyt://article/7621fbf7-80bf-56a6-9d9d-47777eda52c1",
      url: "https://www.nytimes.com/2024/07/21/opinion/biden-aoc-democratic-elites.html",
      id: 100000009583267,
      asset_id: 100000009583267,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 07:40:16",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "United States Politics and Government;Presidential Election of 2024;Polls and Public Opinion;Age, Chronological;Debates (Political);Presidents and Presidency (US);Biden, Joseph R Jr;Trump, Donald J;Ocasio-Cortez, Alexandria;Democratic Party",
      column: null,
      byline: "By Ezra Klein",
      type: "Article",
      title: "Democratic Elites Were Slow to See What Voters Already Knew",
      abstract: "Be skeptical when you hear that this is all a plot.",
      des_facet: [
        "United States Politics and Government",
        "Presidential Election of 2024",
        "Polls and Public Opinion",
        "Age, Chronological",
        "Debates (Political)",
        "Presidents and Presidency (US)",
      ],
      org_facet: ["Democratic Party"],
      per_facet: [
        "Biden, Joseph R Jr",
        "Trump, Donald J",
        "Ocasio-Cortez, Alexandria",
      ],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Damon Winter/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21klein-vwlg/21klein-vwlg-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21klein-vwlg/21klein-vwlg-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21klein-vwlg/21klein-vwlg-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/285cea27-179e-5dd3-b2b6-b043b7c0947f",
      url: "https://www.nytimes.com/2024/07/21/us/politics/kamala-harris.html",
      id: 100000009583709,
      asset_id: 100000009583709,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-22 02:25:19",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "United States Politics and Government;Presidential Election of 2024;Vice Presidents and Vice Presidency (US);Harris, Kamala D;Biden, Joseph R Jr;Democratic Party",
      column: null,
      byline: "By Michael D. Shear",
      type: "Article",
      title:
        "After a Shaky Start, Harris Is Suddenly on Brink of Leading Democratic Ticket",
      abstract:
        "Vice President Kamala Harris got off to a rocky start in office. She is now at the heart of a political drama that could make her the first woman of color to become a major party presidential nominee.",
      des_facet: [
        "United States Politics and Government",
        "Presidential Election of 2024",
        "Vice Presidents and Vice Presidency (US)",
      ],
      org_facet: ["Democratic Party"],
      per_facet: ["Harris, Kamala D", "Biden, Joseph R Jr"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "In the wake of President Biden’s announcement, uncertainty swirled about whether other prominent and ambitious Democrats would seek to challenge Vice President Kamala Harris for the nomination at the party’s convention in Chicago next month.",
          copyright: "Erin Schaff/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21DC-KAMALAHARRIS-jcbv/21DC-KAMALAHARRIS-jcbv-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21DC-KAMALAHARRIS-jcbv/21DC-KAMALAHARRIS-jcbv-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21DC-KAMALAHARRIS-jcbv/21DC-KAMALAHARRIS-jcbv-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/c7ef9623-269b-5872-a671-680cd5ced62d",
      url: "https://www.nytimes.com/2024/07/21/us/politics/vance-trump-campaign-rally.html",
      id: 100000009584227,
      asset_id: 100000009584227,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 15:36:00",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Presidential Election of 2024;Vice Presidents and Vice Presidency (US);Vance, J D;Trump, Donald J;Pence, Mike;Grand Rapids (Mich)",
      column: null,
      byline: "By Shawn McCreesh",
      type: "Article",
      title:
        "On the Trail With Trump, Vance Shows He Knows His Place: Offstage, Mostly",
      abstract:
        "JD Vance, the Republican nominee for vice president, was a mere warm-up act to Donald J. Trump at their first joint rally.",
      des_facet: [
        "Presidential Election of 2024",
        "Vice Presidents and Vice Presidency (US)",
      ],
      org_facet: [],
      per_facet: ["Vance, J D", "Trump, Donald J", "Pence, Mike"],
      geo_facet: ["Grand Rapids (Mich)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Former President Donald J. Trump and his vice-presidential candidate, Senator JD Vance, during a campaign rally in Grand Rapids, Mich., on Saturday.",
          copyright: "Doug Mills/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21pol-trump-chemistry-lzkb/21pol-trump-chemistry-lzkb-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21pol-trump-chemistry-lzkb/21pol-trump-chemistry-lzkb-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21pol-trump-chemistry-lzkb/21pol-trump-chemistry-lzkb-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/d8c3a329-d6bb-5787-b23c-35b8c911246e",
      url: "https://www.nytimes.com/2024/07/21/opinion/trump-administration-chaos.html",
      id: 100000009582169,
      asset_id: 100000009582169,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 21:03:17",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "United States Politics and Government;United States International Relations;Presidential Election of 2024;Defense and Military Forces;Republican National Convention;Rumors and Misinformation;Memory;Crime and Criminals;Biden, Joseph R Jr;Trump, Donald J;Republican Party;Syria;Iran;Russia;United States;Ukraine",
      column: null,
      byline: "By David French",
      type: "Article",
      title: "One of the Republican Convention’s Weirdest Lies",
      abstract:
        "It was one long exercise in creating memories of a Trump term that never existed.",
      des_facet: [
        "United States Politics and Government",
        "United States International Relations",
        "Presidential Election of 2024",
        "Defense and Military Forces",
        "Republican National Convention",
        "Rumors and Misinformation",
        "Memory",
        "Crime and Criminals",
      ],
      org_facet: ["Republican Party"],
      per_facet: ["Biden, Joseph R Jr", "Trump, Donald J"],
      geo_facet: ["Syria", "Iran", "Russia", "United States", "Ukraine"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Thalassa Raasch for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21french-zgwh/21french-zgwh-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21french-zgwh/21french-zgwh-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21french-zgwh/21french-zgwh-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/7b888420-52fe-5292-bcf1-e9ba5fe798a2",
      url: "https://www.nytimes.com/2024/07/21/opinion/joe-biden-drops-out-2024-history.html",
      id: 100000009567293,
      asset_id: 100000009567293,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 21:03:35",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "Presidential Election of 2024;Presidential Election of 1968;Primaries and Caucuses;Democratic National Convention;Biden, Joseph R Jr;Harris, Kamala D;Johnson, Lyndon Baines;Trump, Donald J;Democratic Party;Republican Party;United States",
      column: null,
      byline: "By Frank Bruni",
      type: "Article",
      title: "What Joe Biden Just Did Is Utterly Extraordinary",
      abstract:
        "It’s hard to grasp the historical rarity, emotional agony and fundamental humility of what the president just did.",
      des_facet: [
        "Presidential Election of 2024",
        "Presidential Election of 1968",
        "Primaries and Caucuses",
        "Democratic National Convention",
      ],
      org_facet: ["Democratic Party", "Republican Party"],
      per_facet: [
        "Biden, Joseph R Jr",
        "Harris, Kamala D",
        "Johnson, Lyndon Baines",
        "Trump, Donald J",
      ],
      geo_facet: ["United States"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Damon Winter/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/23/opinion/23bruni1/23bruni1-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/23/opinion/23bruni1/23bruni1-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/23/opinion/23bruni1/23bruni1-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/a7aba839-96ae-515a-a303-887e514cae31",
      url: "https://www.nytimes.com/2024/07/21/nyregion/missing-cows-animal-sanctuary-newfane-ny.html",
      id: 100000009487933,
      asset_id: 100000009487933,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 16:34:29",
      section: "New York",
      subsection: "",
      nytdsection: "new york",
      adx_keywords:
        "Agriculture and Farming;Livestock;Cattle;Animal Abuse, Rights and Welfare;Robberies and Thefts;Trespassing;Threats and Threatening Messages;Demonstrations, Protests and Riots;Social Media;Phoenix, Joaquin;Newfane (NY)",
      column: null,
      byline: "By Christopher Maag",
      type: "Article",
      title: "How Two Wandering Cows Started a Culture War",
      abstract:
        "When Hornee and Blackee strayed from their pasture, they set off a chaotic chain of events involving death threats, chicken rustlers and Joaquin Phoenix. The town of Newfane, N.Y., hasn’t been the same since.",
      des_facet: [
        "Agriculture and Farming",
        "Livestock",
        "Cattle",
        "Animal Abuse, Rights and Welfare",
        "Robberies and Thefts",
        "Trespassing",
        "Threats and Threatening Messages",
        "Demonstrations, Protests and Riots",
        "Social Media",
      ],
      org_facet: [],
      per_facet: ["Phoenix, Joaquin"],
      geo_facet: ["Newfane (NY)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Before she started her animal sanctuary, Ms. Murphy watched videos showing abuse of animals. “What hit me hardest was the cows,” she said.",
          copyright: "Lauren Petracca for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/10/multimedia/FelonyCows-lastgraph-01-qpzf/FelonyCows-lastgraph-01-qpzf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/10/multimedia/FelonyCows-lastgraph-01-qpzf/FelonyCows-lastgraph-01-qpzf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/10/multimedia/FelonyCows-lastgraph-01-qpzf/FelonyCows-lastgraph-01-qpzf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/c40e2dc8-6b67-57e3-afa5-63271744bec8",
      url: "https://www.nytimes.com/2024/07/21/us/national-eucharist-congress-catholics.html",
      id: 100000009578069,
      asset_id: 100000009578069,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 07:59:42",
      section: "U.S.",
      subsection: "",
      nytdsection: "u.s.",
      adx_keywords:
        "Priests;Christians and Christianity;vis-photo;Roman Catholic Church;Indianapolis (Ind);United States",
      column: null,
      byline: "By Ruth Graham and Isadora Kosofsky",
      type: "Article",
      title: "Eight Decades Later, a Celebration of Faith Renewed",
      abstract:
        "More than 50,000 American Catholics gathered at the first National Eucharistic Congress since the 1940s.",
      des_facet: ["Priests", "Christians and Christianity", "vis-photo"],
      org_facet: ["Roman Catholic Church"],
      per_facet: [],
      geo_facet: ["Indianapolis (Ind)", "United States"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Isadora Kosofsky for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21NAT-CATHOLIC-EUCHARIST-promo-mhzf/21NAT-CATHOLIC-EUCHARIST-promo-mhzf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21NAT-CATHOLIC-EUCHARIST-promo-mhzf/21NAT-CATHOLIC-EUCHARIST-promo-mhzf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21NAT-CATHOLIC-EUCHARIST-promo-mhzf/21NAT-CATHOLIC-EUCHARIST-promo-mhzf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/19e33ea6-49c1-5573-8f4a-7dc602cfeadb",
      url: "https://www.nytimes.com/2024/07/21/us/politics/newsom-whitmer-shapiro-biden-drops-out.html",
      id: 100000009584432,
      asset_id: 100000009584432,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 22:52:50",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Presidential Election of 2024;Governors (US);Biden, Joseph R Jr;Newsom, Gavin;Whitmer, Gretchen;Shapiro, Josh (1973- );Democratic Party",
      column: null,
      byline: "By Anushka Patil",
      type: "Article",
      title:
        "What 4 Key Democratic Governors Have Said About Biden Dropping Out",
      abstract:
        "The governors of Pennsylvania, Michigan, California and Illinois have attracted attention as potential contenders to replace President Biden atop the ticket. Here’s what they have said since he dropped out.",
      des_facet: ["Presidential Election of 2024", "Governors (US)"],
      org_facet: ["Democratic Party"],
      per_facet: [
        "Biden, Joseph R Jr",
        "Newsom, Gavin",
        "Whitmer, Gretchen",
        "Shapiro, Josh (1973- )",
      ],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Josh Shapiro of Pennsylvania, Gov. Gretchen Whitmer of Michigan, Gov. Gavin Newsom of California and Gov. JB Pritzker of Illinois. All have been eyed as potential presidential picks.",
          copyright:
            "Kriston Jae Bethel for The New York Times; Sarah Rice for The New York Times; Jim Vondruska for The New York Times; Jamie Kelter Davis for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/us/politics/21election-live-dems-reax2/21election-live-dems-reax2-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/us/politics/21election-live-dems-reax2/21election-live-dems-reax2-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/us/politics/21election-live-dems-reax2/21election-live-dems-reax2-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/c9c3f470-2297-5748-8c30-54250c6168eb",
      url: "https://www.nytimes.com/2024/07/21/us/politics/biden-withdrawal-timeline.html",
      id: 100000009584507,
      asset_id: 100000009584507,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-22 07:14:57",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Presidential Election of 2024;United States Politics and Government;Biden, Joseph R Jr;Donilon, Mike;Ricchetti, Steven;O'Malley Dillon, Jennifer;Zients, Jeffrey D",
      column: null,
      byline:
        "By Katie Rogers, Michael D. Shear, Peter Baker and Zolan Kanno-Youngs",
      type: "Article",
      title: "Inside the Weekend When Biden Decided to Withdraw",
      abstract:
        "President Biden did not tell most of his staff until a minute before making his announcement to the world on social media on Sunday. Vice President Kamala Harris, whom Mr. Biden went on to endorse, also learned of his decision on Sunday.",
      des_facet: [
        "Presidential Election of 2024",
        "United States Politics and Government",
      ],
      org_facet: [],
      per_facet: [
        "Biden, Joseph R Jr",
        "Donilon, Mike",
        "Ricchetti, Steven",
        "O'Malley Dillon, Jennifer",
        "Zients, Jeffrey D",
      ],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "From right to left, the Biden advisers Mike Donilon, Steve Ricchetti and Jen O’Malley Dillon leaving a meeting with Senate Democrats in Washington earlier this month.",
          copyright: "Haiyun Jiang for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21dc-reconstruct-hbwg/21dc-reconstruct-hbwg-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21dc-reconstruct-hbwg/21dc-reconstruct-hbwg-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21dc-reconstruct-hbwg/21dc-reconstruct-hbwg-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/470bc3f5-cca0-5dff-bda7-83a653f40f68",
      url: "https://www.nytimes.com/2024/07/19/movies/new-movies-this-week-critics.html",
      id: 100000009576828,
      asset_id: 100000009576828,
      source: "New York Times",
      published_date: "2024-07-19",
      updated: "2024-07-19 05:03:12",
      section: "Movies",
      subsection: "",
      nytdsection: "movies",
      adx_keywords: "Movies",
      column: null,
      byline: "By The New York Times",
      type: "Article",
      title: "8 New Movies Our Critics Are Talking About This Week",
      abstract:
        "Whether you’re a casual moviegoer or an avid buff, our reviewers think these films are worth knowing about.",
      des_facet: ["Movies"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "From left, Daisy Edgar-Jones, Anthony Ramos and Glen Powell in “Twisters.”",
          copyright:
            "Melinda Sue Gordon/Universal Pictures, Warner Bros. Pictures & Amblin Entertainment",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/15/multimedia/twisters1-ztfj/twisters1-ztfj-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/15/multimedia/twisters1-ztfj/twisters1-ztfj-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/15/multimedia/twisters1-ztfj/twisters1-ztfj-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/3a146e93-db9a-5467-b341-bffacb6d3970",
      url: "https://www.nytimes.com/2024/07/20/health/listeria-outbreak-deli-meats.html",
      id: 100000009583699,
      asset_id: 100000009583699,
      source: "New York Times",
      published_date: "2024-07-20",
      updated: "2024-07-21 13:24:44",
      section: "Health",
      subsection: "",
      nytdsection: "health",
      adx_keywords:
        "Listeria Monocytogenes;Food Contamination and Poisoning;Bacteria;Deaths (Fatalities);Meat;Delicatessens;Supermarkets and Grocery Stores;States (US);Centers for Disease Control and Prevention;United States",
      column: null,
      byline: "By Emily Schmall",
      type: "Article",
      title: "At Least 2 Dead in Listeria Outbreak Tied to Deli-Sliced Meat",
      abstract:
        "The federal Centers for Disease Control and Prevention said 28 people had been hospitalized with listeria infections across a dozen states.",
      des_facet: [
        "Listeria Monocytogenes",
        "Food Contamination and Poisoning",
        "Bacteria",
        "Deaths (Fatalities)",
        "Meat",
        "Delicatessens",
        "Supermarkets and Grocery Stores",
        "States (US)",
      ],
      org_facet: ["Centers for Disease Control and Prevention"],
      per_facet: [],
      geo_facet: ["United States"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Listeria monocytogenes as seen through an electron microscope.",
          copyright: "BSIP/Universal Images Group, via Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/20/lens/20xp-listeria/20xp-listeria-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/20/lens/20xp-listeria/20xp-listeria-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/20/lens/20xp-listeria/20xp-listeria-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/4c587dc1-6950-5c0b-9306-ea7e4d3f79e7",
      url: "https://www.nytimes.com/2024/07/21/us/politics/biden-replace-harris.html",
      id: 100000009553469,
      asset_id: 100000009553469,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 22:27:05",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Presidential Election of 2024;Biden, Joseph R Jr;Harris, Kamala D",
      column: null,
      byline: "By Adam Nagourney and Jennifer Medina",
      type: "Article",
      title:
        "How Will Democrats Replace Biden at the Top of the Presidential Ticket?",
      abstract:
        "The president cleared the way for a successor. He endorsed Vice President Kamala Harris, but there could still be a contest to determine who the nominee will be.",
      des_facet: ["Presidential Election of 2024"],
      org_facet: [],
      per_facet: ["Biden, Joseph R Jr", "Harris, Kamala D"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "President Biden’s debate performance opened the door to political upheaval heading into the Democratic nominating convention in August.",
          copyright: "Kenny Holston/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/06/28/multimedia/replace-biden-2-sub-gztv/replace-biden-2-sub-gztv-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/06/28/multimedia/replace-biden-2-sub-gztv/replace-biden-2-sub-gztv-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/06/28/multimedia/replace-biden-2-sub-gztv/replace-biden-2-sub-gztv-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/18dd679b-5859-513c-a792-1c7894bca36a",
      url: "https://www.nytimes.com/2024/07/21/us/politics/kamala-harris-trump-polls.html",
      id: 100000009584443,
      asset_id: 100000009584443,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 17:16:59",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Presidential Election of 2024;Polls and Public Opinion;Harris, Kamala D;Trump, Donald J",
      column: null,
      byline: "By Ruth Igielnik",
      type: "Article",
      title: "How Kamala Harris Performs Against Donald Trump in the Polls",
      abstract:
        "The vice president could enter the general election campaign in a better position than President Biden.",
      des_facet: ["Presidential Election of 2024", "Polls and Public Opinion"],
      org_facet: [],
      per_facet: ["Harris, Kamala D", "Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "In recent polling, Ms. Harris trails Mr. Trump 46 percent to 48 percent.",
          copyright:
            "Maddie McGarvey for The New York Times; Erin Schaff/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/us/politics/21election-live-polls1/21election-live-polls1-thumbStandard-v2.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/us/politics/21election-live-polls1/21election-live-polls1-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/us/politics/21election-live-polls1/21election-live-polls1-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/a44316cc-4ca9-5fc8-b57b-7601de7a847b",
      url: "https://www.nytimes.com/2024/07/21/opinion/kamala-harris-joe-biden-drops-out.html",
      id: 100000009583475,
      asset_id: 100000009583475,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 20:41:55",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "United States Politics and Government;Presidential Election of 2024;Presidential Election of 2016;Presidential Election of 2020;Conservatism (US Politics);Democratic Party;Republican Party",
      column: null,
      byline: "By Gail Collins and Bret Stephens",
      type: "Article",
      title: "Can Kamala Harris Step Up? Asking for a Friend.",
      abstract: "What are the alternatives? And about those Republicans ...",
      des_facet: [
        "United States Politics and Government",
        "Presidential Election of 2024",
        "Presidential Election of 2016",
        "Presidential Election of 2020",
        "Conservatism (US Politics)",
      ],
      org_facet: ["Democratic Party", "Republican Party"],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Doug Mills/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21conversation1-gfbv/21conversation1-gfbv-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21conversation1-gfbv/21conversation1-gfbv-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21conversation1-gfbv/21conversation1-gfbv-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/cfe8b0aa-7ccf-5d3b-a0b5-bbbf69e516d9",
      url: "https://www.nytimes.com/2024/07/19/style/lauren-garroni-paul-glove-wedding.html",
      id: 100000009554120,
      asset_id: 100000009554120,
      source: "New York Times",
      published_date: "2024-07-19",
      updated: "2024-07-19 19:45:42",
      section: "Style",
      subsection: "",
      nytdsection: "style",
      adx_keywords: "Weddings and Engagements",
      column: null,
      byline: "By Kaitlin Menza",
      type: "Article",
      title: "Committing to the Bit, and Each Other",
      abstract:
        "Lauren Garroni and Paul Glover met through a “Sex and the City” Instagram account, and just like that, felt a spark.",
      des_facet: ["Weddings and Engagements"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Lauren Garroni and Paul Glover were married on July 13 at the Mulholland Tennis Club in Los Angeles.",
          copyright: "The Curries Photography",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/19VOWS-SCREEN-WRITER-01-wgvp/19VOWS-SCREEN-WRITER-01-wgvp-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/19VOWS-SCREEN-WRITER-01-wgvp/19VOWS-SCREEN-WRITER-01-wgvp-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/19VOWS-SCREEN-WRITER-01-wgvp/19VOWS-SCREEN-WRITER-01-wgvp-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/2b8d113f-93e3-5af6-a330-82d4e62b472e",
      url: "https://www.nytimes.com/2024/07/21/opinion/biden-west-wing-aaron-sorkin.html",
      id: 100000009578385,
      asset_id: 100000009578385,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-21 14:23:19",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "Presidential Election of 2024;United States Politics and Government;Television;Appointments and Executive Changes;Biden, Joseph R Jr;Romney, Mitt;Trump, Donald J;Democratic Party;Republican Party",
      column: null,
      byline: "By Aaron Sorkin",
      type: "Article",
      title:
        "Aaron Sorkin: How I Would Script This Moment for Biden and the Democrats",
      abstract: "What would President Bartlet do?",
      des_facet: [
        "Presidential Election of 2024",
        "United States Politics and Government",
        "Television",
        "Appointments and Executive Changes",
      ],
      org_facet: ["Democratic Party", "Republican Party"],
      per_facet: ["Biden, Joseph R Jr", "Romney, Mitt", "Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Erin Schaff",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21sorkin-bczp/21sorkin-bczp-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21sorkin-bczp/21sorkin-bczp-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/21/multimedia/21sorkin-bczp/21sorkin-bczp-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/9e5e085e-c54f-5f9f-9b77-1f1b11239591",
      url: "https://www.nytimes.com/2024/07/20/us/politics/secret-service-trump-shooting.html",
      id: 100000009583964,
      asset_id: 100000009583964,
      source: "New York Times",
      published_date: "2024-07-20",
      updated: "2024-07-21 23:04:46",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Assassinations and Attempted Assassinations;Presidential Election of 2024;United States Politics and Government;Trump, Donald J;Mayorkas, Alejandro;Cheatle, Kimberly A;Crooks, Thomas Matthew (2003-24);Secret Service;Homeland Security Department;Butler (Pa)",
      column: null,
      byline: "By Zolan Kanno-Youngs and Maggie Haberman",
      type: "Article",
      title:
        "Secret Service Says It Denied Earlier Trump Requests for More Federal Resources",
      abstract:
        "In a reversal, a spokesman said the service had turned down requests from former President Donald J. Trump’s team over the past two years, though he said the requests did not include the recent rally in Pennsylvania.",
      des_facet: [
        "Assassinations and Attempted Assassinations",
        "Presidential Election of 2024",
        "United States Politics and Government",
      ],
      org_facet: ["Secret Service", "Homeland Security Department"],
      per_facet: [
        "Trump, Donald J",
        "Mayorkas, Alejandro",
        "Cheatle, Kimberly A",
        "Crooks, Thomas Matthew (2003-24)",
      ],
      geo_facet: ["Butler (Pa)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Members of the Secret Service responding to extract former President Donald J. Trump after a gunman opened fire during a campaign event in Butler, Pa., last weekend.",
          copyright: "Eric Lee/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/20/multimedia/20dc-trump-secretservice-gqkh/20dc-trump-secretservice-gqkh-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/20/multimedia/20dc-trump-secretservice-gqkh/20dc-trump-secretservice-gqkh-mediumThreeByTwo210-v2.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/20/multimedia/20dc-trump-secretservice-gqkh/20dc-trump-secretservice-gqkh-mediumThreeByTwo440-v2.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/b2e70bec-e0f1-579c-a0ca-e0eda5f1c2d2",
      url: "https://www.nytimes.com/2024/07/21/world/asia/jack-ma-xiao-jianhua.html",
      id: 100000009472681,
      asset_id: 100000009472681,
      source: "New York Times",
      published_date: "2024-07-21",
      updated: "2024-07-22 06:39:22",
      section: "World",
      subsection: "Asia Pacific",
      nytdsection: "world",
      adx_keywords:
        "Corruption (Institutional);Ma, Jack;Xiao Jianhua;Zhao Wei (1976- );Xi Jinping;Alibaba Group Holding Ltd;Alipay;Ant Financial Services Group;Yunfeng Capital;Tomorrow Group;China;Hong Kong",
      column: null,
      byline: "By Michael Forsythe, Katrina Northrop and Eliot Chen",
      type: "Article",
      title:
        "The Billionaire Criminal Who Secretly Profited Off Jack Ma’s Deals",
      abstract:
        "Confidential documents show that Xiao Jianhua, a corrupt investor tied to China’s political elite, backed the country’s most successful and revered entrepreneur.",
      des_facet: ["Corruption (Institutional)"],
      org_facet: [
        "Alibaba Group Holding Ltd",
        "Alipay",
        "Ant Financial Services Group",
        "Yunfeng Capital",
        "Tomorrow Group",
      ],
      per_facet: [
        "Ma, Jack",
        "Xiao Jianhua",
        "Zhao Wei (1976- )",
        "Xi Jinping",
      ],
      geo_facet: ["China", "Hong Kong"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Mark Harris for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/11/multimedia/00china-tomorrow-illo-zcwl/00china-tomorrow-illo-zcwl-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/11/multimedia/00china-tomorrow-illo-zcwl/00china-tomorrow-illo-zcwl-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/11/multimedia/00china-tomorrow-illo-zcwl/00china-tomorrow-illo-zcwl-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/5154e4da-2038-5bdb-b128-69de7414c80b",
      url: "https://www.nytimes.com/2024/07/20/opinion/biden-trump-kamala-harris.html",
      id: 100000009582602,
      asset_id: 100000009582602,
      source: "New York Times",
      published_date: "2024-07-20",
      updated: "2024-07-21 10:43:21",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "Presidential Election of 2024;United States Politics and Government;Polls and Public Opinion;Biden, Joseph R Jr;Obama, Barack;Pelosi, Nancy;Democratic Party",
      column: null,
      byline: "By Maureen Dowd",
      type: "Article",
      title: "Lord Almighty, Joe, Let It Go!",
      abstract: "It’s sad that the president doesn’t see what’s inescapable.",
      des_facet: [
        "Presidential Election of 2024",
        "United States Politics and Government",
        "Polls and Public Opinion",
      ],
      org_facet: ["Democratic Party"],
      per_facet: ["Biden, Joseph R Jr", "Obama, Barack", "Pelosi, Nancy"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Kent Nishimura/Agence France-Presse — Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/20/multimedia/20dowdnew-qtwh/20dowdnew-qtwh-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/20/multimedia/20dowdnew-qtwh/20dowdnew-qtwh-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/20/multimedia/20dowdnew-qtwh/20dowdnew-qtwh-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://interactive/6b281d74-22ff-59fe-a559-5b71da0dd5ab",
      url: "https://www.nytimes.com/interactive/2024/07/19/upshot/flashback.html",
      id: 100000009571788,
      asset_id: 100000009571788,
      source: "New York Times",
      published_date: "2024-07-19",
      updated: "2024-07-20 07:18:11",
      section: "The Upshot",
      subsection: "",
      nytdsection: "the upshot",
      adx_keywords: "Content Type: Quiz",
      column: null,
      byline: "",
      type: "Interactive",
      title: "Flashback: Your Weekly History Quiz, July 20, 2024",
      abstract: "Can you sort 8 historical events?",
      des_facet: ["Content Type: Quiz"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "",
          caption: "",
          copyright: "",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/07/19/upshot/flashback-promo/flashback-promo-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/19/upshot/flashback-promo/flashback-promo-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/07/19/upshot/flashback-promo/flashback-promo-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
  ],
};
